config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  root to: "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
  end
  resources :categories, only: [:index, :show]
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: 'レディース' },
    { id: 2, name: 'メンズ' },
    { id: 3, name: 'ベビー・キッズ' },
    { id: 4, name: 'インテリア・住まい・小物' },
    { id: 5, name: '本・音楽・ゲーム' },
    { id: 6, name: 'おもちゃ・ホビー・グッズ' },
    { id: 7, name: '家電・スマホ・カメラ' },
    { id: 8, name: 'スポーツ・レジャー' },
    { id: 9, name: 'ハンドメイド' },
    { id: 10, name: 'その他' }
  ]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @items = Item.order(created_at: :desc)
  end

  def show
    @items = Item.order(created_at: :desc)
  end
end

app/views/categories/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='category-contents'>
    <h2 class='category-title'>カテゴリー一覧</h2>
    <ul class='category-box'>
      <%# ①全てのカテゴリーが表示されるようにしてください %>
      <%# ②カテゴリーがクリックされたらcategories/show.html.erbが表示されるようにしてください %>
      <li class='category-box__list'><%= link_to("カテゴリー1","/")%></li>
      <li class='category-box__list'><%= link_to("カテゴリー2","/")%></li>
      <li class='category-box__list'><%= link_to("カテゴリー3","/")%></li>
    </ul>
  </div>
  <div class='item-contents'>
    <h2 class='title'>全カテゴリーの商品</h2>
    <ul class='item-lists'>
      <% if @items[0] != nil%>
      <% @items.each do |item|%>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
          <% if item.order != nil %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.shipping_fee_status.fee %></span>
            <div class='star-btn'>
              <%= image_tag "star-icon.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/categories/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='category-contents'>
    <h2 class='category-title'>カテゴリー一覧</h2>
    <ul class='category-box'>
      <%# ①全てのカテゴリーが表示されるようにしてください %>
      <%# ②カテゴリーがクリックされたらcategories/show.html.erbが表示されるようにしてください %>
      <li class='category-box__list'><%= link_to("カテゴリー1","/")%></li>
      <li class='category-box__list'><%= link_to("カテゴリー2","/")%></li>
      <li class='category-box__list'><%= link_to("カテゴリー3","/")%></li>
    </ul>
  </div>
  <div class='item-contents'>
    <%# 現在選択されているカテゴリーに合わせて表示名を変えてください %>
    <h2 class='title'>メンズの商品</h2>
    <ul class='item-lists'>
      <%# 現在選択されているカテゴリーに合わせて表示する商品を変えてください %>
      <% if @items[0] != nil%>
      <% @items.each do |item|%>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
          <% if item.order != nil %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.shipping_fee_status.fee %></span>
            <div class='star-btn'>
              <%= image_tag "star-icon.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>